FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.27-alpine

RUN mkdir -p /media /static && chown -R 1000:1000 /media /static

COPY --from=build /app/dist /usr/share/nginx/html
